# Generated by Django 4.0.4 on 2022-04-13 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savana', '0002_drainrequest_testgcsresourcemodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drainrequest',
            old_name='coordinate',
            new_name='point',
        ),
    ]
