# Generated by Django 4.1.2 on 2022-10-05 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savana', '0003_rename_coordinate_drainrequest_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('label', models.CharField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('RT', 'Retired'), ('IN', 'Initiating'), ('ER', 'Error')], default='IN', max_length=2)),
                ('privacy', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PR', max_length=2)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenPlainsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('RT', 'Retired'), ('IN', 'Initiating'), ('ER', 'Error')], default='IN', max_length=2)),
                ('privacy', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PR', max_length=2)),
                ('mapset', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('RT', 'Retired'), ('IN', 'Initiating'), ('ER', 'Error')], default='IN', max_length=2)),
                ('privacy', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PR', max_length=2)),
                ('model', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='savana.openplainsmodel')),
            ],
        ),
    ]
