# Generated by Django 4.1.2 on 2022-10-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savana', '0004_goal_openplainsmodel_modelgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelgoal',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savana.goal'),
        ),
        migrations.AlterField(
            model_name='modelgoal',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savana.openplainsmodel'),
        ),
    ]
