# Generated by Django 4.1.2 on 2022-10-11 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savana', '0005_modelgoal_goal_alter_modelgoal_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openplainsmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opmodel', to=settings.AUTH_USER_MODEL),
        ),
    ]
