# Generated by Django 4.1.2 on 2022-10-17 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savana', '0006_alter_openplainsmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelgoal',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='savana.openplainsmodel'),
        ),
    ]
