# Generated by Django 4.1.2 on 2022-10-17 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savana', '0008_modelextent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelextent',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='savana.openplainsmodel'),
        ),
    ]
