# Generated by Django 4.1.2 on 2022-11-05 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0006_alter_county_geom'),
        ('savana', '0009_alter_modelextent_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainrequest',
            name='huc12',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='drainrequest',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watershed_analysis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('RD', 'Ready'), ('RT', 'Retired'), ('IN', 'Initiating'), ('ER', 'Error')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='modelextent',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.county'),
        ),
        migrations.AlterField(
            model_name='modelgoal',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('RD', 'Ready'), ('RT', 'Retired'), ('IN', 'Initiating'), ('ER', 'Error')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='openplainsmodel',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('RD', 'Ready'), ('RT', 'Retired'), ('IN', 'Initiating'), ('ER', 'Error')], default='IN', max_length=2),
        ),
    ]
