# Generated by Django 4.1.2 on 2022-11-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savana', '0010_drainrequest_huc12_drainrequest_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openplainsmodel',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
