version: "3.8"

# https://stackoverflow.com/questions/44284484/docker-compose-share-named-volume-between-multiple-containers
# x-services-volume:
#   &services-volume
#   type: bind
#   source: ./actinia-core-data/resources
#   target: ./actinia_core/resources
volumes:
   geoserver-data:
   geo-db-data:
services:
  
  db:
    image: postgis/postgis:13-3.2-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data:Z
      # - pg_tileserv_db:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
   
  actinia-core:
    image: mundialis/actinia-core:4.0.0
    volumes:
      - ./actinia-core-data/grassdb:/actinia_core/grassdb:Z
      - ./actinia-core-data/userdata:/actinia_core/userdata
      - ./actinia-core-data/resources:/actinia_core/resources:Z

      # - *services-volume
    ports:
      - "8088:8088"
    depends_on:
      - redis

  redis:
    image: redis:5.0.4-alpine
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_PASS_FILE=/data/config/.redis
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    ports:
        - "6379:6379"

  django-redis-cache:
    image: redis:5.0.4-alpine
    volumes:
      - ./django_redis_cache:/data
    environment:
      - REDIS_PASS_FILE=/data/config/.redis
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    ports:
        - "6370:6370"

# pg_tileserv:
#   image: pramsey/pg_tileserv:latest-alpine-3.12
#   build:
#     context: ../..
#     dockerfile: Dockerfile.alpine
#     args:
#       VERSION: latest-alpine-3.12
#   container_name: pg_tileserv
#   env_file:
#     - pg_tileserv.env
#   depends_on:
#     - db
#   ports:
#     - 7800:7800

  api:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8005"
    volumes:
      - .:/code
      - ./actinia-core-data/resources:/actinia_core/resources:Z

    ports:
      - "8005:8005"
      - "8010:8010"
    depends_on:
      - db
      - actinia-core
      - django-redis-cache

  celery_worker:
    build:
      context: .
      # dockerfile: ./Dockerfile
    # image: django_celery_example_celery_worker
    command: celery -A api.celery worker --loglevel=INFO
    volumes:
      - .:/code
    env_file:
      - ./api/.env
    depends_on:
      - redis
      - db
      - api
  
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    command: npm start
    volumes:
      # - /code/node_modules
      - ./webapp/:/code
    ports:
      - "3000:3000"
    depends_on:
      - api
  
  terracotta:
    build:
      context: ./terracotta
      dockerfile: Dockerfile
    volumes:
      - ./terracotta/data:/app/data
      # - <<: *services-volume
      #   target: ./app/data
    ports:
      - 5000:5000
      - 5001:5001
        
  titiler:
    build:
      context: ./titiler
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    depends_on:
      - actinia-core

  # Only turn on when needed
  wireshark:
    image: lscr.io/linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    # volumes:
    #   - /path/to/config:/config
    ports:
      #HOST:CONTAINER
      - 3050:3000
    restart: unless-stopped

  geoserver-postgis:
    # build:
    #   context: ./geoserver
    #
    image: kartoza/postgis:14-3.1
    volumes:
      - geo-db-data:/var/lib/postgresql
    ports:
      # - ${POSTGRES_PORT}:5432
      - 32767:5432
    env_file:
      - ./geoserver/.env
    # environment:
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASS=${POSTGRES_PASS}
    #   - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
    #   - FORCE_SSL=TRUE
    restart: on-failure
    healthcheck:
      test: "exit 0"
  geoserver:
    build:
      context: ./geoserver
      dockerfile: Dockerfile
    env_file:
      - ./geoserver/.env
    # image: kartoza/geoserver:2.20.3
    volumes:
        - geoserver-data:/opt/geoserver/data_dir
    restart: on-failure
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver/data_dir/gwc
      - GEOSERVER_ADMIN_PASSWORD=myawesomegeoserver
      - GEOSERVER_ADMIN_USER=admin
      - INITIAL_MEMORY=2G
      - MAXIMUM_MEMORY=4G
    depends_on:
      - geoserver-postgis
        # condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    ports:
      - 8600:8080
      - 8643:8443

  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx/geoserver:/etc/nginx/conf.d:ro
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 200m
  #       max-file: '10'
  #   depends_on:
  #     - geoserver
  #   ports:
  #     - "80:80"