# Generated by Django 4.0.4 on 2022-05-28 02:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huc12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.BigIntegerField(unique=True)),
                ('tnmid', models.CharField(max_length=40)),
                ('metasourceid', models.CharField(max_length=40)),
                ('sourcedatadesc', models.CharField(max_length=100)),
                ('sourceoriginator', models.CharField(max_length=130)),
                ('sourcefeatureid', models.CharField(max_length=40)),
                ('loaddate', models.DateField()),
                ('noncontributingareaacres', models.FloatField()),
                ('noncontributingareasqkm', models.FloatField()),
                ('areasqkm', models.FloatField()),
                ('areaacres', models.FloatField()),
                ('referencegnis_ids', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=120)),
                ('states', models.CharField(max_length=50)),
                ('huc12', models.CharField(max_length=12)),
                ('hutype', models.CharField(choices=[('S', 'Standard'), ('B', 'Closed Basin'), ('F', 'Frontal'), ('M', 'Multiple Outlet'), ('W', 'Water'), ('I', 'Island'), ('U', 'Urban'), ('D', 'Indeterminate')], max_length=1)),
                ('humod', models.CharField(max_length=30)),
                ('tohuc', models.CharField(max_length=16)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
