# Generated by Django 4.0.3 on 2022-03-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=250)),
                ('resource_id', models.CharField(max_length=250)),
                ('process_results', models.JSONField(default=dict, verbose_name='process_results')),
                ('message', models.CharField(max_length=50)),
                ('accept_timestamp', models.DecimalField(decimal_places=6, max_digits=19)),
                ('accept_datetime', models.CharField(max_length=250)),
                ('timestamp', models.DecimalField(decimal_places=6, max_digits=19)),
                ('time_delta', models.DecimalField(decimal_places=6, max_digits=19)),
                ('datetime', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TestGCSResourceModel',
            fields=[
                ('user_id', models.CharField(max_length=250)),
                ('resource_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('geotiff_result', models.ImageField(upload_to='geotiff_results')),
            ],
        ),
    ]
