/*
 * Filename: ExportType.js
 * Project: TomorrowNow
 * File Created: Wednesday May 25th 2022
 * Author: Corey White (smortopahri@gmail.com)
 * Maintainer: Corey White
 * -----
 * Last Modified: Wed May 25 2022
 * Modified By: Corey White
 * -----
 * License: GPLv3
 * 
 * Copyright (c) 2022 TomorrowNow
 * 
 * TomorrowNow is an open-source geospatial participartory modeling platform
 * to enable stakeholder engagment in socio-environmental decision-makeing.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 * 
 */

/**
 * @description The type of the output. In case of the *file* option only text files are supported for export. In addition the *$file::unique_id* option must be used in the value parameter to export a file that was generated by a GRASS GIS module. Exported text and vector files will always be compressed with zip.
 * @param {String} name The export format type being accessed.
 */
 export class ExportType {
    static raster = new ExportType('raster');
    static vector = new ExportType('vector');
    static file = new ExportType('file');
    static strds = new ExportType('strds');

    constructor(name) {
        this.name = name;
    }

    toString() {
        return `ExportType.${this.name}`
    }
}
